### ISSUE TITLE
Allow prompts/tests to be in separate files

### ISSUE THREAD

**Issue by tbuckley** [tbuckley/evals-pwa#8]

**Comment by tbuckley** [comment]
Proposed ordering:
- [ ] Prompt can be a .txt file
- [ ] Test can be a .yaml file
- [ ] Var can be a .txt file
- [x] Var can be a .png/.jpg/.jpeg file
- [ ] Support globs within prompt/test item
- [ ] Vars can be a .yaml file (string instead of an object)
- [ ] Allow prompts/tests to be a glob (string instead of array of strings)

Examples:

```yaml
prompts:
  - file:///prompt.txt

tests:
  - file:///test.yaml
  - vars:
      foo: file:///vars/foo.txt
      bar: file:///vars/bar.png
```

Globs
```yaml
prompts:
  - file:///prompts/*.txt

tests:
  - file:///tests/*.yaml
```

Changing the structure
```yaml
prompts: file:///prompts/*.txt
tests: file:///tests/*.yaml

# OR
tests:
  - vars: file:///vars/test1.yaml
```
